// Custom License Key Generation & Validation Module
// Generates keys in the format: XXXX-XXXX-XXXX-XXXX
// Includes a checksum to validate if a key was generated by our system without hitting the database.

const SECRET_SALT = "NXN_INFRA_2026_ENTERPRISE_KEY_SALT";

function getCharValue(char: string): number {
  const chars = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";
  return chars.indexOf(char);
}

function getCharFromValue(value: number): string {
  const chars = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";
  return chars[value % chars.length];
}

// Simple checksum algorithm
function calculateChecksum(part1: string, part2: string, part3: string): string {
  let sum = 0;
  const combined = part1 + part2 + part3 + SECRET_SALT;
  for (let i = 0; i < combined.length; i++) {
    sum += combined.charCodeAt(i) * (i + 1);
  }
  
  // Generate a 4-character checksum
  let checksum = "";
  for (let i = 0; i < 4; i++) {
    checksum += getCharFromValue(sum + i * 17); // arbitrary prime for diffusion
  }
  return checksum;
}

function generateRandomPart(): string {
  const chars = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";
  let result = "";
  for (let i = 0; i < 4; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}

export function generateSecureLicenseKey(): string {
  const part1 = generateRandomPart();
  const part2 = generateRandomPart();
  const part3 = generateRandomPart();
  
  const checksum = calculateChecksum(part1, part2, part3);
  
  return `${part1}-${part2}-${part3}-${checksum}`;
}

export function validateLicenseKeyFormat(key: string): boolean {
  if (!key || typeof key !== 'string') return false;
  
  const parts = key.split('-');
  if (parts.length !== 4) return false;
  
  for (const part of parts) {
    if (part.length !== 4) return false;
    if (!/^[0-9A-Z]+$/.test(part)) return false;
  }
  
  const checksum = calculateChecksum(parts[0], parts[1], parts[2]);
  return checksum === parts[3];
}
